spring.application.name=Elections

spring:
datasource:
url: jdbc:postgresql://127.0.0.1:5434/analytics_db?currentSchema=analytics
username: postgres
password: postgres
driverClassName: org.postgresql.Driver
hikari:
maximum-pool-size: 10
minimum-idle: 2
idle-timeout: 30000
max-lifetime: 1800000
connection-timeout: 30000
