server.port=8095
#server.servlet.context-path= /onwelo

# Application Name
spring.application.name=Elections

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5444/elections
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driverClassName=org.postgresql.Driver

# Hikari Connection Pool Settings
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000