########################################################################################################################
#
# These are deployment steps for docker compose:
# 1. Used for both: offsite and GitLab CI/CD deployments.
# 2. This configuration is also used to set up deployment variables for containers.
#
########################################################################################################################

services:

  elections-postgresql:
    image: elections-postgresql
    container_name: elections-postgresql
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 3GB
    build:
      context: ./../elections-postgresql
      dockerfile: Dockerfile.elections
    environment:
      - PGUSER=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5444:5432'
    networks:
      - elections_network
    volumes:
      - elections_data:/var/lib/postgresql/data
    command: |
      postgres
        -c checkpoint_completion_target=0.9
        -c default_statistics_target=400
        -c effective_io_concurrency=200
        -c random_page_cost=1.0
        -c 'max_connections=250'

volumes:
  elections_data:
    driver: local

networks:
  elections_network:
    name: elections-network
    driver: bridge