/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.1 		*/
/*  Created On : 12-sty-2024 12:46:02 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Analytics"."Address" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."AddressAlternativeName" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."AnalyticalContext" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."Association" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."AssociationSourceQueryAssociation" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."AssociationUIViewAssocation" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."Authority" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."Binary" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."BinarySourceQueryAssociation" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."BinaryUIViewAssociation" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."BorderCross" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."BorderCrossingPoint" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."BusinessEntity" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."BusinessEntityAlternativeName" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."BusinessEntityLegalChanges" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."CarRegistrationCertificate" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."Case" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."Citizenship" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."ContactDetails" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."Country" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."Document" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."DocumentSourceQueryAssociation" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."DocumentUIViewAssociation" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."Event" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."EventDocumentAssociation" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."EventLocationAssociation" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."EventSourceQueryAssociation" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."EventUIViewAssociation" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."Facility" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."FacilityOrganisationAssociation" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."ForeignerIdentityCard" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."GeoPoint" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."GovernmentOrganisation" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."IdentityDocument" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."Location" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."LocationSourceQueryAssociation" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."LocationUIViewAssociation" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."Migration" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."Name" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."NameAlternative" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."Object" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."ObjectBinaryAssociation" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."ObjectDocumentAssociation" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."ObjectEventAssociation" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."ObjectLocationAssociation" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."ObjectSourceQueryAssociation" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."ObjectUIViewAssociation" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."Organisation" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."OrganisationOrganisationAssociation" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."OrganisationPersonAssociation" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."Passport" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."Person" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."PersonalAccess" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."PersonPersonAssociation" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."Picture" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."Place" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."PlaceAlternativeName" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."PolishIdentityCard" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."RoadBorderCrossing" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."RoadBorderCrossingPoint" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."RoadCheckPointTransition" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."RoadVehicle" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."RoadVehicleDictionary" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."RoadVehicleInsurancePolicy" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."RoadVehicleRegistration" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."RoadVehicleRegistrationCertificate" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."RoadVehicleRegistrationCertificateWithdrawal" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."RoadVehicleRegistrationIdentity" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."RoadVehicleRegistrationPlate" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."SourceQueryContext" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."Surname" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."SurnameAlternative" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."UIViewContext" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."User" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."UserCaseAssociation" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."Vehicle" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."VehicleObjectAssociation" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."Visa" CASCADE
;

DROP TABLE IF EXISTS "Analytics"."VisaApplication" CASCADE
;

/* Create Tables */

CREATE TABLE "Analytics"."Address"
(
  id uuid NOT NULL,
  street varchar(255) NULL,
  house varchar(20) NULL,
  apartment varchar(20) NULL,
  city varchar(150) NULL,
  commune varchar(255) NULL,
  county varchar(255) NULL,
  voivodeship varchar(150) NULL,
  postal_code varchar(12) NULL,
  comment varchar(2000) NULL
)
;

CREATE TABLE "Analytics"."AddressAlternativeName"
(
  id uuid NOT NULL,
  type varchar(20) NOT NULL,
  address_id uuid NOT NULL,
  value varchar(255) NULL
)
;

CREATE TABLE "Analytics"."AnalyticalContext"
(
  id uuid NOT NULL,
  type varchar(40) NOT NULL
)
;

CREATE TABLE "Analytics"."Association"
(
  id uuid NOT NULL,
  type varchar(40) NULL,
  analytical_context_id uuid NOT NULL
)
;

CREATE TABLE "Analytics"."AssociationSourceQueryAssociation"
(
  id uuid NOT NULL,
  association_id uuid NOT NULL,
  source_query_id uuid NOT NULL
)
;

CREATE TABLE "Analytics"."AssociationUIViewAssocation"
(
  id uuid NOT NULL,
  association_id uuid NOT NULL,
  ui_view_context_id uuid NOT NULL,
  is_root boolean NULL
)
;

CREATE TABLE "Analytics"."Authority"
(
  id uuid NOT NULL,
  type varchar(20) NOT NULL,
  code varchar(50) NULL
)
;

CREATE TABLE "Analytics"."Binary"
(
  id uuid NOT NULL,
  type varchar(20) NOT NULL,
  analytical_context_id uuid NOT NULL
)
;

CREATE TABLE "Analytics"."BinarySourceQueryAssociation"
(
  id uuid NOT NULL,
  binary_id uuid NOT NULL,
  source_query_id uuid NOT NULL
)
;

CREATE TABLE "Analytics"."BinaryUIViewAssociation"
(
  id uuid NOT NULL,
  binary_id uuid NOT NULL,
  ui_view_context_id uuid NOT NULL,
  is_root boolean NULL
)
;

CREATE TABLE "Analytics"."BorderCross"
(
  id uuid NOT NULL,
  type varchar(50) NOT NULL,
  direction varchar(20) NULL,
  event_time timestamp with time zone NULL
)
;

CREATE TABLE "Analytics"."BorderCrossingPoint"
(
  id uuid NOT NULL,
  type varchar(40) NOT NULL,
  name varchar(255) NULL
)
;

CREATE TABLE "Analytics"."BusinessEntity"
(
  id uuid NOT NULL,
  type varchar(30) NOT NULL,
  other_identifucation_number varchar(50) NULL,
  printed_name varchar(150) NULL,
  unofficial_name varchar(255) NULL,
  krs_registration_number varchar(50) NULL,
  is_opp boolean NULL,
  website_address varchar(128) NULL,
  email_address varchar(50) NULL,
  krs_entity_validity_date date NULL,
  krs_share_capital varchar(50) NULL,
  krs_share_capital_paid varchar(50) NULL,
  krs_share_capital_contributions varchar(2000) NULL,
  krs_number_of_shares varchar(50) NULL,
  krs_share_value varchar(50) NULL,
  krs_shares_issues varchar(2000) NULL,
  krs_representation_body_name varchar(50) NULL,
  krs_representation_body_description varchar(50) NULL,
  krs_supervision_body_name varchar(50) NULL
)
;

CREATE TABLE "Analytics"."BusinessEntityAlternativeName"
(
  id uuid NOT NULL,
  business_entity_id uuid NOT NULL,
  value varchar(255) NULL
)
;

CREATE TABLE "Analytics"."BusinessEntityLegalChanges"
(
  id uuid NOT NULL,
  change varchar(2000) NOT NULL,
  business_entity_id uuid NOT NULL
)
;

CREATE TABLE "Analytics"."CarRegistrationCertificate"
(
  id uuid NOT NULL,
  type varchar(40) NOT NULL,
  status varchar(40) NOT NULL,
  is_duplicate boolean NULL,
  is_valid boolean NULL
)
;

CREATE TABLE "Analytics"."Case"
(
  id uuid NOT NULL,
  type varchar(40) NOT NULL
)
;

CREATE TABLE "Analytics"."Citizenship"
(
  id uuid NOT NULL,
  code varchar(50) NOT NULL,
  value varchar(255) NOT NULL
)
;

CREATE TABLE "Analytics"."ContactDetails"
(
  id uuid NOT NULL,
  contact_type varchar(30) NULL,
  source_type varchar(30) NULL,
  value varchar(255) NULL,
  person_id uuid NOT NULL
)
;

CREATE TABLE "Analytics"."Country"
(
  id uuid NOT NULL,
  code varchar(50) NULL,
  name varchar(255) NOT NULL,
  "code2ISO" varchar(50) NULL,
  "code3ISO" varchar(50) NULL,
  "codeICAO" varchar(50) NULL
)
;

CREATE TABLE "Analytics"."Document"
(
  id uuid NOT NULL,
  type varchar(20) NOT NULL,
  analytical_context_id uuid NOT NULL
)
;

CREATE TABLE "Analytics"."DocumentSourceQueryAssociation"
(
  id uuid NOT NULL,
  document_id uuid NOT NULL,
  source_query_id uuid NOT NULL
)
;

CREATE TABLE "Analytics"."DocumentUIViewAssociation"
(
  id uuid NOT NULL,
  document_id uuid NOT NULL,
  ui_view_context_id uuid NOT NULL,
  is_root boolean NULL
)
;

CREATE TABLE "Analytics"."Event"
(
  id uuid NOT NULL,
  type varchar(50) NOT NULL,
  analytical_context_id uuid NOT NULL
)
;

CREATE TABLE "Analytics"."EventDocumentAssociation"
(
  id uuid NOT NULL,
  type varchar(40) NULL,
  event_id uuid NOT NULL,
  document_id uuid NOT NULL
)
;

CREATE TABLE "Analytics"."EventLocationAssociation"
(
  id uuid NOT NULL,
  type varchar(50) NOT NULL,
  event_id uuid NOT NULL,
  location_id uuid NOT NULL
)
;

CREATE TABLE "Analytics"."EventSourceQueryAssociation"
(
  id uuid NOT NULL,
  event_id uuid NOT NULL,
  source_query_id uuid NOT NULL
)
;

CREATE TABLE "Analytics"."EventUIViewAssociation"
(
  id uuid NOT NULL,
  event_id uuid NOT NULL,
  ui_view_context_id uuid NOT NULL,
  is_root boolean NULL
)
;

CREATE TABLE "Analytics"."Facility"
(
  id uuid NOT NULL,
  type varchar(30) NOT NULL
)
;

CREATE TABLE "Analytics"."FacilityOrganisationAssociation"
(
  id uuid NOT NULL,
  type varchar(50) NULL,
  organisation_id uuid NOT NULL,
  facility_id uuid NOT NULL
)
;

CREATE TABLE "Analytics"."ForeignerIdentityCard"
(
  id uuid NOT NULL,
  document_name varchar(100) NULL,
  issuer_country_id uuid NULL,
  comments varchar(2000) NULL
)
;

CREATE TABLE "Analytics"."GeoPoint"
(
  id uuid NOT NULL
)
;

CREATE TABLE "Analytics"."GovernmentOrganisation"
(
  id uuid NOT NULL
)
;

CREATE TABLE "Analytics"."IdentityDocument"
(
  id uuid NOT NULL,
  type varchar(20) NOT NULL,
  number varchar(50) NULL,
  issued date NULL,
  valid_to date NULL
)
;

CREATE TABLE "Analytics"."Location"
(
  id uuid NOT NULL,
  type varchar(20) NOT NULL,
  country_id uuid NULL,
  analytical_context_id uuid NOT NULL,
  latitude double precision NULL,
  longitude double precision NULL
)
;

CREATE TABLE "Analytics"."LocationSourceQueryAssociation"
(
  id uuid NOT NULL,
  location_id uuid NOT NULL,
  source_query_id uuid NOT NULL
)
;

CREATE TABLE "Analytics"."LocationUIViewAssociation"
(
  id uuid NOT NULL,
  location_id uuid NOT NULL,
  ui_view_context_id uuid NOT NULL,
  is_root boolean NULL
)
;

CREATE TABLE "Analytics"."Migration"
(
  id uuid NOT NULL,
  person_id uuid NOT NULL,
  arrival date NULL,
  departure date NULL,
  estimated_residence_period date NULL,
  is_permanent boolean NULL,
  country_id uuid NULL
)
;

CREATE TABLE "Analytics"."Name"
(
  id uuid NOT NULL,
  type varchar(20) NOT NULL,
  value varchar(255) NOT NULL,
  person_id uuid NOT NULL
)
;

CREATE TABLE "Analytics"."NameAlternative"
(
  id uuid NOT NULL,
  value varchar(255) NOT NULL,
  name_id uuid NOT NULL
)
;

CREATE TABLE "Analytics"."Object"
(
  id uuid NOT NULL,
  type varchar(20) NOT NULL,
  analytical_context_id uuid NOT NULL
)
;

CREATE TABLE "Analytics"."ObjectBinaryAssociation"
(
  id uuid NOT NULL,
  type varchar(40) NOT NULL,
  object_id uuid NOT NULL,
  binary_id uuid NOT NULL
)
;

CREATE TABLE "Analytics"."ObjectDocumentAssociation"
(
  id uuid NOT NULL,
  object_id uuid NOT NULL,
  document_id uuid NOT NULL,
  type varchar(50) NOT NULL
)
;

CREATE TABLE "Analytics"."ObjectEventAssociation"
(
  id uuid NOT NULL,
  type varchar(50) NOT NULL,
  border_cross_person_type varchar(30) NULL,
  object_id uuid NOT NULL,
  event_id uuid NOT NULL
)
;

CREATE TABLE "Analytics"."ObjectLocationAssociation"
(
  id uuid NOT NULL,
  object_id uuid NOT NULL,
  location_id uuid NOT NULL,
  type varchar(40) NOT NULL,
  "from" date NULL,
  "to" date NULL
)
;

CREATE TABLE "Analytics"."ObjectSourceQueryAssociation"
(
  id uuid NOT NULL,
  object_id uuid NOT NULL,
  source_query_id uuid NOT NULL
)
;

CREATE TABLE "Analytics"."ObjectUIViewAssociation"
(
  id uuid NOT NULL,
  object_id uuid NOT NULL,
  ui_view_context_id uuid NOT NULL,
  is_root boolean NULL
)
;

CREATE TABLE "Analytics"."Organisation"
(
  id uuid NOT NULL,
  type varchar(20) NOT NULL,
  name varchar(255) NULL,
  regon varchar(12) NULL,
  nip varchar(20) NULL,
  country_id uuid NULL
)
;

CREATE TABLE "Analytics"."OrganisationOrganisationAssociation"
(
  id uuid NOT NULL,
  type varchar(30) NOT NULL,
  subject_organisation_id uuid NOT NULL,
  object_organisation_id uuid NOT NULL,
  krs_all_shares_owner boolean NULL,
  krs_entity_creation_type varchar(50) NULL,
  krs_entity_creation_description varchar(2000) NULL
)
;

CREATE TABLE "Analytics"."OrganisationPersonAssociation"
(
  id uuid NOT NULL,
  type varchar(40) NULL,
  organisation_id uuid NOT NULL,
  person_id uuid NOT NULL,
  krs_spzoo_share_value varchar(50) NULL,
  krs_spzoo_has_all_shares boolean NULL,
  krs_entity_representation_type varchar(50) NULL,
  krs_entity_representation_suspension boolean NULL,
  krs_entity_supervision_type varchar(50) NULL,
  krs_entity_supervision_suspension boolean NULL,
  krs_entity_proxy_type varchar(50) NULL
)
;

CREATE TABLE "Analytics"."Passport"
(
  id uuid NOT NULL,
  type varchar(30) NULL,
  status varchar(30) NULL,
  is_valid boolean NULL,
  mrz_code_line_01 varchar(50) NULL,
  mrx_code_line_02 varchar(50) NULL,
  application_number varchar(50) NULL,
  sticker_series varchar(12) NULL,
  sticker_number varchar(50) NULL,
  sticker_is_diplomatic boolean NULL,
  sticker_comment varchar(2000) NULL
)
;

CREATE TABLE "Analytics"."Person"
(
  id uuid NOT NULL,
  educational_establishment varchar(255) NULL,
  eyes_colour varchar(20) NULL,
  foreigner_status varchar(100) NULL,
  gender varchar(20) NULL,
  height integer NULL,
  home_country_id uuid NULL,
  martial_status varchar(20) NULL,
  occupation varchar(255) NULL,
  other_id varchar(255) NULL,
  pesel varchar(11) NULL,
  birth_citizenship_id uuid NULL,
  birth_country_id uuid NULL,
  birth_date date NULL,
  fathers_name varchar(100) NULL,
  mothers_name varchar(100) NULL,
  birth_place_id uuid NULL,
  death_corpse_finding_date date NULL,
  death_date date NULL,
  death_date_descriptive varchar(255) NULL,
  death_invalidation_date date NULL
)
;

CREATE TABLE "Analytics"."PersonalAccess"
(
  id uuid NOT NULL
)
;

CREATE TABLE "Analytics"."PersonPersonAssociation"
(
  id uuid NOT NULL,
  type varchar(40) NOT NULL,
  object_person_id uuid NOT NULL,
  subject_person_id uuid NOT NULL,
  started date NULL,
  finished date NULL
)
;

CREATE TABLE "Analytics"."Picture"
(
  id uuid NOT NULL,
  file_type varchar(50) NOT NULL,
  content bytea NOT NULL
)
;

CREATE TABLE "Analytics"."Place"
(
  id uuid NOT NULL,
  code varchar(50) NULL,
  name varchar(255) NULL
)
;

CREATE TABLE "Analytics"."PlaceAlternativeName"
(
  id uuid NOT NULL,
  place_id uuid NOT NULL,
  value varchar(255) NULL
)
;

CREATE TABLE "Analytics"."PolishIdentityCard"
(
  id uuid NOT NULL,
  status varchar(20) NULL
)
;

CREATE TABLE "Analytics"."RoadBorderCrossing"
(
  id uuid NOT NULL
)
;

CREATE TABLE "Analytics"."RoadBorderCrossingPoint"
(
  id uuid NOT NULL
)
;

CREATE TABLE "Analytics"."RoadCheckPointTransition"
(
  id uuid NOT NULL,
  transition_timestamp timestamp without time zone NULL
)
;

CREATE TABLE "Analytics"."RoadVehicle"
(
  id uuid NOT NULL,
  brand_id uuid NULL,
  curb_weight double precision NULL,
  engine_power double precision NULL,
  engine_size double precision NULL,
  first_registration date NULL,
  first_registration_abroad date NULL,
  first_registration_poland date NULL,
  main_purpose varchar(50) NULL,
  manufacture_year integer NULL,
  model varchar(50) NULL,
  next_technical_check date NULL,
  registration_type_id uuid NULL,
  status_id uuid NULL,
  type_id uuid NULL,
  subtype_id uuid NULL,
  vin varchar(50) NULL,
  abroad_status_previous_vin varchar(50) NULL,
  abroad_status_registration_country_id uuid NULL,
  abroad_status_registration_number varchar(50) NULL
)
;

CREATE TABLE "Analytics"."RoadVehicleDictionary"
(
  id uuid NOT NULL,
  dictionary_type varchar(50) NULL,
  code varchar(50) NOT NULL,
  short_description varchar(100) NULL,
  long_description varchar(2000) NULL,
  status varchar(50) NULL
)
;

CREATE TABLE "Analytics"."RoadVehicleInsurancePolicy"
(
  id uuid NOT NULL,
  policy_number varchar(50) NULL,
  valid_from date NULL,
  valid_to date NULL,
  road_vehicle_id uuid NOT NULL
)
;

CREATE TABLE "Analytics"."RoadVehicleRegistration"
(
  id uuid NOT NULL,
  registration date NULL,
  cancelation date NULL,
  registration_type uuid NULL
)
;

CREATE TABLE "Analytics"."RoadVehicleRegistrationCertificate"
(
  id uuid NOT NULL,
  type uuid NULL,
  status uuid NULL,
  is_duplicate boolean NULL,
  is_valid boolean NULL
)
;

CREATE TABLE "Analytics"."RoadVehicleRegistrationCertificateWithdrawal"
(
  id uuid NOT NULL,
  purpose uuid NULL,
  is_technical_verification_required boolean NULL,
  road_vehicle_registration_certificate_id uuid NOT NULL
)
;

CREATE TABLE "Analytics"."RoadVehicleRegistrationIdentity"
(
  id uuid NOT NULL,
  type uuid NULL,
  identity_number varchar(100) NULL,
  is_duplicate boolean NULL,
  road_vehicle_registration_certificate_id uuid NOT NULL
)
;

CREATE TABLE "Analytics"."RoadVehicleRegistrationPlate"
(
  id varchar(50) NOT NULL,
  type uuid NULL,
  number varchar(50) NOT NULL,
  road_vehicle_id uuid NOT NULL,
  issuing_country_id uuid NULL
)
;

CREATE TABLE "Analytics"."SourceQueryContext"
(
  id uuid NOT NULL,
  analytical_context_id uuid NULL
)
;

CREATE TABLE "Analytics"."Surname"
(
  id uuid NOT NULL,
  type varchar(20) NOT NULL,
  value varchar(255) NOT NULL,
  person_id uuid NOT NULL
)
;

CREATE TABLE "Analytics"."SurnameAlternative"
(
  id uuid NOT NULL,
  value varchar(255) NOT NULL,
  surname_id uuid NOT NULL
)
;

CREATE TABLE "Analytics"."UIViewContext"
(
  id uuid NOT NULL,
  type varchar(50) NOT NULL
)
;

CREATE TABLE "Analytics"."User"
(
  id uuid NOT NULL
)
;

CREATE TABLE "Analytics"."UserCaseAssociation"
(
  id uuid NOT NULL,
  user_id uuid NOT NULL,
  case_id uuid NOT NULL
)
;

CREATE TABLE "Analytics"."Vehicle"
(
  id uuid NOT NULL,
  type varchar(30) NOT NULL
)
;

CREATE TABLE "Analytics"."VehicleObjectAssociation"
(
  id uuid NOT NULL,
  type varchar(50) NULL,
  created_at date NULL,
  vehicle_id uuid NOT NULL,
  object_id uuid NOT NULL
)
;

CREATE TABLE "Analytics"."Visa"
(
  id uuid NOT NULL,
  type varchar(40) NOT NULL,
  valid_from date NULL,
  visa_comment varchar(2000) NULL,
  territorial_validity varchar(255) NULL,
  duration_of_stay integer NULL,
  number_of_entries integer NULL,
  sticker_status varchar(40) NULL,
  sticker_comment varchar(2000) NULL,
  passport_id uuid NOT NULL
)
;

CREATE TABLE "Analytics"."VisaApplication"
(
  id uuid NOT NULL,
  destination_country_id uuid NULL,
  intended_days_of_visit integer NULL,
  intended_entry_date date NULL,
  intended_exit_date date NULL,
  invitation_from date NULL,
  invitation_to date NULL,
  invitation_number varchar(100) NULL,
  is_eu_family_member boolean NULL,
  mode_of_transportation varchar(150) NULL,
  number_of_entries varchar(40) NULL,
  number_of_persons integer NULL,
  other_polish_visas varchar(1000) NULL,
  past_foreign_travels varchar(1000) NULL,
  purpose_code varchar(40) NULL,
  purpose_other varchar(1000) NULL,
  subbmited date NULL,
  requested_visa_type varchar(40) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Analytics"."Address" ADD CONSTRAINT "PK_Address"
  PRIMARY KEY (id)
;

CREATE INDEX "IXFK_Address_Location" ON "Analytics"."Address" (id ASC)
;

ALTER TABLE "Analytics"."AddressAlternativeName" ADD CONSTRAINT "PK_AddressAlternativeName"
  PRIMARY KEY (id)
;

ALTER TABLE "Analytics"."AddressAlternativeName" ADD CONSTRAINT "CH_AddressAlternativeName" CHECK (type IN ('CITY', 'STREET', 'NOS'))
;

CREATE INDEX "IXFK_AddressAlternativeName_Address" ON "Analytics"."AddressAlternativeName" (address_id ASC)
;

ALTER TABLE "Analytics"."AnalyticalContext" ADD CONSTRAINT "PK_AnalyticalContext"
  PRIMARY KEY (id)
;

ALTER TABLE "Analytics"."AnalyticalContext" ADD CONSTRAINT "CH_AnalyticalContext" CHECK (type IN ('CASE', 'PERSONAL_ACCESS', 'NOS'))
;

ALTER TABLE "Analytics"."Association" ADD CONSTRAINT "PK_Association"
  PRIMARY KEY (id)
;

ALTER TABLE "Analytics"."Association" ADD CONSTRAINT "CH_Association" CHECK (type IN ('OBJECT_LOCATION', 'OBJECT_DOCUMENT', 'PERSON_PERSON', 'OBJECT_BINARY', 'EVENT_LOCATION', 'FACILITY_ORGANISATION', 'OBJECT_EVENT', 'EVENT_DOCUMENT', 'ORGANISATION_PERSON', 'ORGANISATION_ORGANISATION'))
;

CREATE INDEX "IXFK_Association_AnalyticalContext" ON "Analytics"."Association" (analytical_context_id ASC)
;

ALTER TABLE "Analytics"."AssociationSourceQueryAssociation" ADD CONSTRAINT "PK_AssociationSourceQueryAssociation"
  PRIMARY KEY (id)
;

CREATE INDEX "IXFK_AssociationSourceQueryAssociation_Association" ON "Analytics"."AssociationSourceQueryAssociation" (association_id ASC)
;

CREATE INDEX "IXFK_AssociationSourceQueryAssociation_SourceQueryContext" ON "Analytics"."AssociationSourceQueryAssociation" (source_query_id ASC)
;

ALTER TABLE "Analytics"."AssociationUIViewAssocation" ADD CONSTRAINT "PK_AssociationUIViewAssocation"
  PRIMARY KEY (id)
;

CREATE INDEX "IXFK_AssociationUIViewAssocation_Association" ON "Analytics"."AssociationUIViewAssocation" (association_id ASC)
;

CREATE INDEX "IXFK_AssociationUIViewAssocation_UIViewContext" ON "Analytics"."AssociationUIViewAssocation" (ui_view_context_id ASC)
;

ALTER TABLE "Analytics"."Authority" ADD CONSTRAINT "PK_Authority"
  PRIMARY KEY (id)
;

ALTER TABLE "Analytics"."Authority" ADD CONSTRAINT "CH_Authority" CHECK (type IN ('NOS'))
;

CREATE INDEX "IXFK_Authority_GovernmentOrganisation" ON "Analytics"."Authority" (id ASC)
;

ALTER TABLE "Analytics"."Binary" ADD CONSTRAINT "PK_Binary"
  PRIMARY KEY (id)
;

ALTER TABLE "Analytics"."Binary" ADD CONSTRAINT "CH_Binary" CHECK (type IN ('PICTURE', 'NOS'))
;

CREATE INDEX "IXFK_Binary_AnalyticalContext" ON "Analytics"."Binary" (analytical_context_id ASC)
;

ALTER TABLE "Analytics"."BinarySourceQueryAssociation" ADD CONSTRAINT "PK_BinarySourceQueryAssociation"
  PRIMARY KEY (id)
;

CREATE INDEX "IXFK_BinarySourceQueryAssociation_Binary" ON "Analytics"."BinarySourceQueryAssociation" (binary_id ASC)
;

CREATE INDEX "IXFK_BinarySourceQueryAssociation_SourceQueryContext" ON "Analytics"."BinarySourceQueryAssociation" (source_query_id ASC)
;

ALTER TABLE "Analytics"."BinaryUIViewAssociation" ADD CONSTRAINT "PK_BinaryUIViewAssociation"
  PRIMARY KEY (id)
;

CREATE INDEX "IXFK_BinaryUIViewAssociation_Binary" ON "Analytics"."BinaryUIViewAssociation" (binary_id ASC)
;

CREATE INDEX "IXFK_BinaryUIViewAssociation_UIViewContext" ON "Analytics"."BinaryUIViewAssociation" (ui_view_context_id ASC)
;

ALTER TABLE "Analytics"."BorderCross" ADD CONSTRAINT "PK_BorderCross"
  PRIMARY KEY (id)
;

ALTER TABLE "Analytics"."BorderCross" ADD CONSTRAINT "CH_BorderCross_01" CHECK (type IN ('ROAD_BORDER_CROSS', 'NOS'))
;

ALTER TABLE "Analytics"."BorderCross" ADD CONSTRAINT "CH_BorderCross_02" CHECK (direction in ('ENTRY', 'EXIT', 'CHECK', 'NOS'))
;

CREATE INDEX "IXFK_BorderCross_Event" ON "Analytics"."BorderCross" (id ASC)
;

ALTER TABLE "Analytics"."BorderCrossingPoint" ADD CONSTRAINT "PK_BorderCrossingPoint"
  PRIMARY KEY (id)
;

ALTER TABLE "Analytics"."BorderCrossingPoint" ADD CONSTRAINT "CH_BorderCrossingPoint" CHECK (type IN ('ROAD_BORDER_CROSS_POINT', 'NOS'))
;

CREATE INDEX "IXFK_BorderCrossingPoint_Facility" ON "Analytics"."BorderCrossingPoint" (id ASC)
;

ALTER TABLE "Analytics"."BusinessEntity" ADD CONSTRAINT "PK_BusinessEntity"
  PRIMARY KEY (id)
;

ALTER TABLE "Analytics"."BusinessEntity" ADD CONSTRAINT "CH_BusinessEntity_Type" CHECK (type IN ('NOS'))
;

CREATE INDEX "IXFK_BusinessEntity_Organisation" ON "Analytics"."BusinessEntity" (id ASC)
;

ALTER TABLE "Analytics"."BusinessEntityAlternativeName" ADD CONSTRAINT "PK_BusinessEntityAlternativeName"
  PRIMARY KEY (id)
;

CREATE INDEX "IXFK_BusinessEntityAlternativeName_BusinessEntity" ON "Analytics"."BusinessEntityAlternativeName" (business_entity_id ASC)
;

ALTER TABLE "Analytics"."BusinessEntityLegalChanges" ADD CONSTRAINT "PK_BusinessEntityLegalChanges"
  PRIMARY KEY (id)
;

CREATE INDEX "IXFK_BusinessEntityLegalChanges_BusinessEntity" ON "Analytics"."BusinessEntityLegalChanges" (business_entity_id ASC)
;

ALTER TABLE "Analytics"."CarRegistrationCertificate" ADD CONSTRAINT "PK_CarRegistrationCertificate"
  PRIMARY KEY (id)
;

CREATE INDEX "IXFK_CarRegistrationCertificate_IdentityDocument" ON "Analytics"."CarRegistrationCertificate" (id ASC)
;

ALTER TABLE "Analytics"."Case" ADD CONSTRAINT "PK_Case"
  PRIMARY KEY (id)
;

ALTER TABLE "Analytics"."Case" ADD CONSTRAINT "CH_Case_AnalyticalContext" CHECK (type IN ('CASE', 'WORKING_COPY', 'NOS'))
;

CREATE INDEX "IXFK_Case_AnalyticalContext" ON "Analytics"."Case" (id ASC)
;

ALTER TABLE "Analytics"."Citizenship" ADD CONSTRAINT "PK_Citizenship"
  PRIMARY KEY (id)
;

ALTER TABLE "Analytics"."ContactDetails" ADD CONSTRAINT "PK_ContactDetails"
  PRIMARY KEY (id)
;

ALTER TABLE "Analytics"."ContactDetails" ADD CONSTRAINT "CH_ContactDetails_01" CHECK (contact_type IN ('PHONE', 'EMAIL', 'FAX', 'NOS'))
;

ALTER TABLE "Analytics"."ContactDetails" ADD CONSTRAINT "CH_ContactDetails_02" CHECK (source_type IN ('HOME_RESIDENCE', 'VISA_CONTACT'))
;

CREATE INDEX "IXFK_ContactDetails_Person" ON "Analytics"."ContactDetails" (person_id ASC)
;

ALTER TABLE "Analytics"."Country" ADD CONSTRAINT "PK_Country"
  PRIMARY KEY (id)
;

ALTER TABLE "Analytics"."Document" ADD CONSTRAINT "PK_Document"
  PRIMARY KEY (id)
;

ALTER TABLE "Analytics"."Document" ADD CONSTRAINT "CH_Document" CHECK (type IN ('COURT_DOC', 'IDENTITY_DOC'))
;

CREATE INDEX "IXFK_Document_AnalyticalContext" ON "Analytics"."Document" (analytical_context_id ASC)
;

ALTER TABLE "Analytics"."DocumentSourceQueryAssociation" ADD CONSTRAINT "PK_DocumentSourceQueryAssociation"
  PRIMARY KEY (id)
;

CREATE INDEX "IXFK_DocumentSourceQueryAssociation_Document" ON "Analytics"."DocumentSourceQueryAssociation" (document_id ASC)
;

CREATE INDEX "IXFK_DocumentSourceQueryAssociation_SourceQueryContext" ON "Analytics"."DocumentSourceQueryAssociation" (source_query_id ASC)
;

ALTER TABLE "Analytics"."DocumentUIViewAssociation" ADD CONSTRAINT "PK_DocumentUIViewAssociation"
  PRIMARY KEY (id)
;

CREATE INDEX "IXFK_DocumentUIViewAssociation_Document" ON "Analytics"."DocumentUIViewAssociation" (document_id ASC)
;

CREATE INDEX "IXFK_DocumentUIViewAssociation_UIViewContext" ON "Analytics"."DocumentUIViewAssociation" (ui_view_context_id ASC)
;

ALTER TABLE "Analytics"."Event" ADD CONSTRAINT "PK_Event"
  PRIMARY KEY (id)
;

ALTER TABLE "Analytics"."Event" ADD CONSTRAINT "CH_Event" CHECK (type IN ('BORDER_CROSS', 'ROAD_VEHICLE_REGISTRATION', 'ROAD_CHECK_POINT_TRANSITION', 'VISA_APPLICATION', 'NOS'))
;

CREATE INDEX "IXFK_Event_AnalyticalContext" ON "Analytics"."Event" (analytical_context_id ASC)
;

ALTER TABLE "Analytics"."EventDocumentAssociation" ADD CONSTRAINT "PK_EventDocumentAssociation"
  PRIMARY KEY (id)
;

ALTER TABLE "Analytics"."EventDocumentAssociation" ADD CONSTRAINT "CH_EventDocumentAssociation" CHECK (type IN ('VISA_APPLICATION_TRAVEL_DOCUMENT', 'NOS'))
;

CREATE INDEX "IXFK_EventDocumentAssociation_Association" ON "Analytics"."EventDocumentAssociation" (id ASC)
;

CREATE INDEX "IXFK_EventDocumentAssociation_Document" ON "Analytics"."EventDocumentAssociation" (document_id ASC)
;

CREATE INDEX "IXFK_EventDocumentAssociation_Event" ON "Analytics"."EventDocumentAssociation" (event_id ASC)
;

ALTER TABLE "Analytics"."EventLocationAssociation" ADD CONSTRAINT "PK_EventLocationAssociation"
  PRIMARY KEY (id)
;

ALTER TABLE "Analytics"."EventLocationAssociation" ADD CONSTRAINT "CH_EventLocationAssociation" CHECK (type IN ('VISA_APPLICATION_SUBMISSION', 'VEHICLE_ANPRS_REGISTRATION_POINT', 'NOS'))
;

CREATE INDEX "IXFK_EventLocationAssociation_Association" ON "Analytics"."EventLocationAssociation" (id ASC)
;

CREATE INDEX "IXFK_EventLocationAssociation_Event" ON "Analytics"."EventLocationAssociation" (event_id ASC)
;

CREATE INDEX "IXFK_EventLocationAssociation_Location" ON "Analytics"."EventLocationAssociation" (location_id ASC)
;

ALTER TABLE "Analytics"."EventSourceQueryAssociation" ADD CONSTRAINT "PK_EventSourceQueryAssociation"
  PRIMARY KEY (id)
;

CREATE INDEX "IXFK_EventSourceQueryAssociation_Event" ON "Analytics"."EventSourceQueryAssociation" (event_id ASC)
;

CREATE INDEX "IXFK_EventSourceQueryAssociation_SourceQueryContext" ON "Analytics"."EventSourceQueryAssociation" (source_query_id ASC)
;

ALTER TABLE "Analytics"."EventUIViewAssociation" ADD CONSTRAINT "PK_EventUIViewAssociation"
  PRIMARY KEY (id)
;

CREATE INDEX "IXFK_EventUIViewAssociation_Event" ON "Analytics"."EventUIViewAssociation" (event_id ASC)
;

CREATE INDEX "IXFK_EventUIViewAssociation_UIViewContext" ON "Analytics"."EventUIViewAssociation" (ui_view_context_id ASC)
;

ALTER TABLE "Analytics"."Facility" ADD CONSTRAINT "PK_Facility"
  PRIMARY KEY (id)
;

ALTER TABLE "Analytics"."Facility" ADD CONSTRAINT "CH_Facility" CHECK (type IN ('BORDER_CROSS_POINT', 'NOS'))
;

CREATE INDEX "IXFK_Facility_Object" ON "Analytics"."Facility" (id ASC)
;

ALTER TABLE "Analytics"."FacilityOrganisationAssociation" ADD CONSTRAINT "PK_FacilityOrganisationAssociation"
  PRIMARY KEY (id)
;

ALTER TABLE "Analytics"."FacilityOrganisationAssociation" ADD CONSTRAINT "CH_FacilityOrganisationAssociation" CHECK (type IN ('BORDER_CROSS_POINT_ORGANISTATION', 'NOS'))
;

CREATE INDEX "IXFK_FacilityOrganisationAssociation_Association" ON "Analytics"."FacilityOrganisationAssociation" (id ASC)
;

CREATE INDEX "IXFK_FacilityOrganisationAssociation_Facility" ON "Analytics"."FacilityOrganisationAssociation" (facility_id ASC)
;

CREATE INDEX "IXFK_FacilityOrganisationAssociation_Organisation" ON "Analytics"."FacilityOrganisationAssociation" (organisation_id ASC)
;

ALTER TABLE "Analytics"."ForeignerIdentityCard" ADD CONSTRAINT "PK_ForeignerIdentityCard"
  PRIMARY KEY (id)
;

CREATE INDEX "IXFK_ForeignerIdentityCard_Country" ON "Analytics"."ForeignerIdentityCard" (issuer_country_id ASC)
;

CREATE INDEX "IXFK_ForeignerIdentityCard_IdentityDocument" ON "Analytics"."ForeignerIdentityCard" (id ASC)
;

ALTER TABLE "Analytics"."GeoPoint" ADD CONSTRAINT "PK_GeoPoint"
  PRIMARY KEY (id)
;

CREATE INDEX "IXFK_GeoPoint_Location" ON "Analytics"."GeoPoint" (id ASC)
;

ALTER TABLE "Analytics"."GovernmentOrganisation" ADD CONSTRAINT "PK_GovernmentOrganisation"
  PRIMARY KEY (id)
;

CREATE INDEX "IXFK_GovernmentOrganisation_Organisation" ON "Analytics"."GovernmentOrganisation" (id ASC)
;

ALTER TABLE "Analytics"."IdentityDocument" ADD CONSTRAINT "PK_IdentityDocument"
  PRIMARY KEY (id)
;

ALTER TABLE "Analytics"."IdentityDocument" ADD CONSTRAINT "CH_IdentityDocument" CHECK (type IN ('PASSPORT', 'POLISH_ID', 'FOREIGN_ID', 'VISA', 'CAR_CERTIFICATE'))
;

CREATE INDEX "IXFK_IdentityDocument_Document" ON "Analytics"."IdentityDocument" (id ASC)
;

ALTER TABLE "Analytics"."Location" ADD CONSTRAINT "PK_Location"
  PRIMARY KEY (id)
;

ALTER TABLE "Analytics"."Location" ADD CONSTRAINT "CH_Location" CHECK (type IN ('PLACE', 'ADDRESS', 'GEO_POINT', 'NOS'))
;

CREATE INDEX "IXFK_Location_AnalyticalContext" ON "Analytics"."Location" (analytical_context_id ASC)
;

CREATE INDEX "IXFK_Location_Country" ON "Analytics"."Location" (country_id ASC)
;

ALTER TABLE "Analytics"."LocationSourceQueryAssociation" ADD CONSTRAINT "PK_LocationSourceQueryAssociation"
  PRIMARY KEY (id)
;

CREATE INDEX "IXFK_LocationSourceQueryAssociation_Location" ON "Analytics"."LocationSourceQueryAssociation" (location_id ASC)
;

CREATE INDEX "IXFK_LocationSourceQueryAssociation_SourceQueryContext" ON "Analytics"."LocationSourceQueryAssociation" (source_query_id ASC)
;

ALTER TABLE "Analytics"."LocationUIViewAssociation" ADD CONSTRAINT "PK_LocationUIViewAssociation"
  PRIMARY KEY (id)
;

CREATE INDEX "IXFK_LocationUIViewAssociation_Location" ON "Analytics"."LocationUIViewAssociation" (location_id ASC)
;

CREATE INDEX "IXFK_LocationUIViewAssociation_UIViewContext" ON "Analytics"."LocationUIViewAssociation" (ui_view_context_id ASC)
;

ALTER TABLE "Analytics"."Migration" ADD CONSTRAINT "PK_Migration"
  PRIMARY KEY (id)
;

CREATE INDEX "IXFK_Migration_Country" ON "Analytics"."Migration" (country_id ASC)
;

CREATE INDEX "IXFK_Migration_Person" ON "Analytics"."Migration" (person_id ASC)
;

ALTER TABLE "Analytics"."Name" ADD CONSTRAINT "PK_Name"
  PRIMARY KEY (id)
;

ALTER TABLE "Analytics"."Name" ADD CONSTRAINT "CH_Name_Type" CHECK (type in ('FIRST', 'SECOND', 'OTHER', 'PREVIOUS'))
;

CREATE INDEX "IXFK_Name_Person" ON "Analytics"."Name" (person_id ASC)
;

ALTER TABLE "Analytics"."NameAlternative" ADD CONSTRAINT "PK_NameAlternative"
  PRIMARY KEY (id)
;

CREATE INDEX "IXFK_NameAlternative_Name" ON "Analytics"."NameAlternative" (name_id ASC)
;

ALTER TABLE "Analytics"."Object" ADD CONSTRAINT "PK_Object"
  PRIMARY KEY (id)
;

ALTER TABLE "Analytics"."Object" ADD CONSTRAINT "CH_Obejct_Type" CHECK (type in ('PERSON', 'ORGANISATION', 'VEHICLE', 'FACILITY', 'NOS'))
;

CREATE INDEX "IXFK_Object_AnalyticalContext" ON "Analytics"."Object" (analytical_context_id ASC)
;

ALTER TABLE "Analytics"."ObjectBinaryAssociation" ADD CONSTRAINT "PK_ObjectBinaryAssociation"
  PRIMARY KEY (id)
;

ALTER TABLE "Analytics"."ObjectBinaryAssociation" ADD CONSTRAINT "CH_ObjectBinaryAssociation" CHECK (type IN ('PICTURE_PERSON_FACIAL', 'PICTURE_PERSON_FINGERPRINTS', 'PICTURE_PERSON_LIVE', 'PICTURE_PERSON_SIGNATURE', 'PICTURE_TRAVEL_DOCUMENT_ELECTRONIC_LAYER', 'PICTURE_TRAVEL_DOCUMENT_PAGE', 'PICTURE_VEHICLE_FRONT', 'PICTURE_VEHICLE_REAR', 'PICTURE_VISIT_DOCUMENT_ELECTRONIC_LAYER', 'PICTURE_VISIT_DOCUMENT_PAGE', 'NOS'))
;

CREATE INDEX "IXFK_ObjectBinaryAssociation_Association" ON "Analytics"."ObjectBinaryAssociation" (id ASC)
;

CREATE INDEX "IXFK_ObjectBinaryAssociation_Binary" ON "Analytics"."ObjectBinaryAssociation" (binary_id ASC)
;

CREATE INDEX "IXFK_ObjectBinaryAssociation_Object" ON "Analytics"."ObjectBinaryAssociation" (object_id ASC)
;

ALTER TABLE "Analytics"."ObjectDocumentAssociation" ADD CONSTRAINT "PK_ObjectDocumentAssociation"
  PRIMARY KEY (id)
;

ALTER TABLE "Analytics"."ObjectDocumentAssociation" ADD CONSTRAINT "CH_ObjectDocumentAssociation" CHECK (type IN ('ROAD_VEHICLE_IDENTITY_DOCUMENT', 'DOCUMENT_ISSUING_AUTHORITY', 'PASSPORT_RECEIVER', 'PASSPORT_STORING_AUTHORITY', 'PERSON_IDENTITY', 'PERSON_TRAVEL_DOCUMENT', 'NOS'))
;

CREATE INDEX "IXFK_ObjectDocumentAssociation_Association" ON "Analytics"."ObjectDocumentAssociation" (id ASC)
;

CREATE INDEX "IXFK_ObjectDocumentAssociation_Document" ON "Analytics"."ObjectDocumentAssociation" (document_id ASC)
;

CREATE INDEX "IXFK_ObjectDocumentAssociation_Object" ON "Analytics"."ObjectDocumentAssociation" (object_id ASC)
;

ALTER TABLE "Analytics"."ObjectEventAssociation" ADD CONSTRAINT "PK_ObjectEventAssociation"
  PRIMARY KEY (id)
;

ALTER TABLE "Analytics"."ObjectEventAssociation" ADD CONSTRAINT "CH_ObjectEventAssociation_01" CHECK (type IN ('VISA_APPLICATION_AUTHORITY', 'VISA_APPLICATION_HOST', 'VISA_APPLICATION_APPLICANT', 'VISA_APPLICATION_BORDER_CROSS_POINT', 'BORDER_CROSS_FACILITY', 'BORDER_CROSS_VEHICLE', 'BORDER_CROSS_PERSON', 'ROAD_VEHICLE_REGISTRATION_AUTHORITY', 'ROAD_VEHICLE_REGISTRATION_VEHICLE', 'ROAD_VEHICLE_ANPRS_CROSSING', 'NOS'))
;

ALTER TABLE "Analytics"."ObjectEventAssociation" ADD CONSTRAINT "CH_ObjectEventAssociation_02" CHECK (border_cross_person_type IN ('PASSANGER', 'DRIVER', 'OTHER_PERSON', 'NOS'))
;

CREATE INDEX "IXFK_ObjectEventAssociation_Association" ON "Analytics"."ObjectEventAssociation" (id ASC)
;

CREATE INDEX "IXFK_ObjectEventAssociation_Event" ON "Analytics"."ObjectEventAssociation" (event_id ASC)
;

CREATE INDEX "IXFK_ObjectEventAssociation_Object" ON "Analytics"."ObjectEventAssociation" (object_id ASC)
;

ALTER TABLE "Analytics"."ObjectLocationAssociation" ADD CONSTRAINT "PK_ObjectLocationAssociation"
  PRIMARY KEY (id)
;

ALTER TABLE "Analytics"."ObjectLocationAssociation" ADD CONSTRAINT "CH_ObjectLocationAssociation" CHECK (type IN ('PERSON_HOME_ADDRESS', 'PERSON_TEMPORARY_ADDRESS', 'VISA_APPLICANT_ADDRESS', 'VISA_EU_STAYING_ADDRESS', 'VISA_HOST_ADDRESS', 'AUTHORITY_LOCATION', 'BUSINESS_ENTITY_REGISTRATION_ADDRESS', 'BUSINESS_ENTITY_REGISTRATION_HEADQUARTERS', 'NOS'))
;

CREATE INDEX "IXFK_ObjectLocationAssociation_Association" ON "Analytics"."ObjectLocationAssociation" (id ASC)
;

CREATE INDEX "IXFK_ObjectLocationAssociation_Location" ON "Analytics"."ObjectLocationAssociation" (location_id ASC)
;

CREATE INDEX "IXFK_ObjectLocationAssociation_Object" ON "Analytics"."ObjectLocationAssociation" (object_id ASC)
;

ALTER TABLE "Analytics"."ObjectSourceQueryAssociation" ADD CONSTRAINT "PK_ObjectSourceQueryAssociation"
  PRIMARY KEY (id)
;

CREATE INDEX "IXFK_ObjectSourceQueryAssociation_Object" ON "Analytics"."ObjectSourceQueryAssociation" (object_id ASC)
;

CREATE INDEX "IXFK_ObjectSourceQueryAssociation_SourceQueryContext" ON "Analytics"."ObjectSourceQueryAssociation" (source_query_id ASC)
;

ALTER TABLE "Analytics"."ObjectUIViewAssociation" ADD CONSTRAINT "PK_ObjectUIViewAssociation"
  PRIMARY KEY (id)
;

CREATE INDEX "IXFK_ObjectUIViewAssociation_Object" ON "Analytics"."ObjectUIViewAssociation" (object_id ASC)
;

CREATE INDEX "IXFK_ObjectUIViewAssociation_UIViewContext" ON "Analytics"."ObjectUIViewAssociation" (ui_view_context_id ASC)
;

ALTER TABLE "Analytics"."Organisation" ADD CONSTRAINT "PK_Organisation"
  PRIMARY KEY (id)
;

ALTER TABLE "Analytics"."Organisation" ADD CONSTRAINT "CH_Organisation" CHECK (type IN ('GOV_ORG', 'PRV_SECTOR'))
;

CREATE INDEX "IXFK_Organisation_Country" ON "Analytics"."Organisation" (country_id ASC)
;

CREATE INDEX "IXFK_Organisation_Object" ON "Analytics"."Organisation" (id ASC)
;

ALTER TABLE "Analytics"."OrganisationOrganisationAssociation" ADD CONSTRAINT "PK_OrganisationOrganisationAssociation"
  PRIMARY KEY (id)
;

ALTER TABLE "Analytics"."OrganisationOrganisationAssociation" ADD CONSTRAINT "CH_OrganisationOrganisationAssociation" CHECK (type IN ('KRS_SOLE_SHAREHOLDER', 'KRS_DIVISION', 'KRS_ENTITY_CREATION_PART', 'NOS'))
;

CREATE INDEX "IXFK_OrganisationOrganisationAssociation_Association" ON "Analytics"."OrganisationOrganisationAssociation" (id ASC)
;

CREATE INDEX "IXFK_OrganisationOrganisationAssociation_Organisation" ON "Analytics"."OrganisationOrganisationAssociation" (subject_organisation_id ASC)
;

CREATE INDEX "IXFK_OrganisationOrganisationAssociation_Organisation_02" ON "Analytics"."OrganisationOrganisationAssociation" (object_organisation_id ASC)
;

ALTER TABLE "Analytics"."OrganisationPersonAssociation" ADD CONSTRAINT "PK_OrganisationPersonAssociation"
  PRIMARY KEY (id)
;

ALTER TABLE "Analytics"."OrganisationPersonAssociation" ADD CONSTRAINT "CH_OrganisationPersonAssociation" CHECK (type IN ('ORGANISATION_CONTACT_PERSON', 'ORGANISATION_SHAREHOLDER', 'ORGANISATION_REPRESENATION_BODY', 'ORGANISATION_SUPERVISION_BODY', 'ORGANISATION_PROXY_BODY', 'NOS'))
;

CREATE INDEX "IXFK_OrganisationPersonAssociation_Association" ON "Analytics"."OrganisationPersonAssociation" (id ASC)
;

CREATE INDEX "IXFK_OrganisationPersonAssociation_Organisation" ON "Analytics"."OrganisationPersonAssociation" (organisation_id ASC)
;

CREATE INDEX "IXFK_OrganisationPersonAssociation_Person" ON "Analytics"."OrganisationPersonAssociation" (person_id ASC)
;

ALTER TABLE "Analytics"."Passport" ADD CONSTRAINT "PK_Passport"
  PRIMARY KEY (id)
;

ALTER TABLE "Analytics"."Passport" ADD CONSTRAINT "CH_PassportType" CHECK (type IN ('PASZPORT_BIOMETRYCZNY', 'PASZPORT_DYPLOMATYCZNY', 'PASZPORT_SLUZBOWY', 'PASZPORT_TYMCZASOWY', 'NOS'))
;

ALTER TABLE "Analytics"."Passport" ADD CONSTRAINT "CH_PassportStatus" CHECK (status IN ('GOTOWY_DO_WYDANIA_OBYWATELOWI', 'PRZEKAZANY_KURIEROWI', 'PRZYJETY_NA_STAN', 'SPERSONALIZOWANY', 'UNIEWAZNIONY', 'WYDANY_OBYWATELOWI', 'WYPOCZTOWANY', 'NOS'))
;

CREATE INDEX "IXFK_Passport_IdentityDocument" ON "Analytics"."Passport" (id ASC)
;

ALTER TABLE "Analytics"."Person" ADD CONSTRAINT "PK_Person"
  PRIMARY KEY (id)
;

ALTER TABLE "Analytics"."Person" ADD CONSTRAINT "CH_Person_Eyes_Colour" CHECK (eyes_colour IN ('BLUE', 'GRAY', 'HAZEL', 'BLACK', 'GREEN', 'BROWN', 'RED', 'MULTICOLOUR', 'NOS'))
;

ALTER TABLE "Analytics"."Person" ADD CONSTRAINT "CH_Person_Gender" CHECK (gender IN ('MALE', 'FEMALE', 'NOS'))
;

ALTER TABLE "Analytics"."Person" ADD CONSTRAINT "CH_Person_Martial_Status" CHECK (martial_status IN ('SINGLE', 'MARRIED', 'WIDOWED', 'DIVORCED', 'NOS'))
;

CREATE INDEX "IXFK_Person_Citizenship" ON "Analytics"."Person" (birth_citizenship_id ASC)
;

CREATE INDEX "IXFK_Person_Country" ON "Analytics"."Person" (home_country_id ASC)
;

CREATE INDEX "IXFK_Person_Country_02" ON "Analytics"."Person" (birth_country_id ASC)
;

CREATE INDEX "IXFK_Person_Object" ON "Analytics"."Person" (id ASC)
;

CREATE INDEX "IXFK_Person_Place" ON "Analytics"."Person" (birth_place_id ASC)
;

ALTER TABLE "Analytics"."PersonalAccess" ADD CONSTRAINT "PK_PersonalAccess"
  PRIMARY KEY (id)
;

CREATE INDEX "IXFK_PersonalAccess_AnalyticalContext" ON "Analytics"."PersonalAccess" (id ASC)
;

CREATE INDEX "IXFK_PersonalAccess_User" ON "Analytics"."PersonalAccess" (id ASC)
;

ALTER TABLE "Analytics"."PersonPersonAssociation" ADD CONSTRAINT "PK_PersonPersonAssociation"
  PRIMARY KEY (id)
;

ALTER TABLE "Analytics"."PersonPersonAssociation" ADD CONSTRAINT "CH_PersonPersonAssociation" CHECK (type IN ('SPOUSE', 'FATHER', 'MOTHER', 'PARENT', 'NOS'))
;

CREATE INDEX "IXFK_PersonPersonAssociation_Association" ON "Analytics"."PersonPersonAssociation" (id ASC)
;

CREATE INDEX "IXFK_PersonPersonAssociation_Person" ON "Analytics"."PersonPersonAssociation" (object_person_id ASC)
;

CREATE INDEX "IXFK_PersonPersonAssociation_Person_02" ON "Analytics"."PersonPersonAssociation" (subject_person_id ASC)
;

ALTER TABLE "Analytics"."Picture" ADD CONSTRAINT "PK_Picture"
  PRIMARY KEY (id)
;

ALTER TABLE "Analytics"."Picture" ADD CONSTRAINT "CH_PictureFileType" CHECK (file_type IN ('JPG', 'PNG', 'NOS'))
;

CREATE INDEX "IXFK_Picture_Binary" ON "Analytics"."Picture" (id ASC)
;

ALTER TABLE "Analytics"."Place" ADD CONSTRAINT "PK_Place"
  PRIMARY KEY (id)
;

CREATE INDEX "IXFK_Place_Location" ON "Analytics"."Place" (id ASC)
;

ALTER TABLE "Analytics"."PlaceAlternativeName" ADD CONSTRAINT "PK_PlaceAlternativeName"
  PRIMARY KEY (id)
;

CREATE INDEX "IXFK_PlaceAlternativeName_Place" ON "Analytics"."PlaceAlternativeName" (place_id ASC)
;

ALTER TABLE "Analytics"."PolishIdentityCard" ADD CONSTRAINT "PK_PolishIdentityCard"
  PRIMARY KEY (id)
;

ALTER TABLE "Analytics"."PolishIdentityCard" ADD CONSTRAINT "CH_PolishIdentityCard" CHECK (status IN ('ODMOWA_ART_32', 'ODMOWA_ART_52', 'ODWOLANIE', 'PRZYJETY_PRZEZ_URZAD', 'SPERSONALIZOWANY', 'UNIEWAZNIONY', 'UNIEWAZNIONY_RECZNY', 'WPROWADZONY_RECZNIE', 'WYDANY', 'WYSLANY', 'ZAWIESZONY', 'NOS'))
;

CREATE INDEX "IXFK_PolishIdentityCard_IdentityDocument" ON "Analytics"."PolishIdentityCard" (id ASC)
;

ALTER TABLE "Analytics"."RoadBorderCrossing" ADD CONSTRAINT "PK_RoadBorderCrossing"
  PRIMARY KEY (id)
;

CREATE INDEX "IXFK_RoadBorderCrossing_BorderCross" ON "Analytics"."RoadBorderCrossing" (id ASC)
;

ALTER TABLE "Analytics"."RoadBorderCrossingPoint" ADD CONSTRAINT "PK_RoadBorderCrossingPoint"
  PRIMARY KEY (id)
;

CREATE INDEX "IXFK_RoadBorderCrossingPoint_BorderCrossingPoint" ON "Analytics"."RoadBorderCrossingPoint" (id ASC)
;

ALTER TABLE "Analytics"."RoadCheckPointTransition" ADD CONSTRAINT "PK_RoadCheckPointTransition"
  PRIMARY KEY (id)
;

CREATE INDEX "IXFK_RoadCheckPointTransition_Event" ON "Analytics"."RoadCheckPointTransition" (id ASC)
;

ALTER TABLE "Analytics"."RoadVehicle" ADD CONSTRAINT "PK_RoadVehicle"
  PRIMARY KEY (id)
;

CREATE INDEX "IXFK_RoadVehicle_Country" ON "Analytics"."RoadVehicle" (abroad_status_registration_country_id ASC)
;

CREATE INDEX "IXFK_RoadVehicle_RoadVehicleFeature" ON "Analytics"."RoadVehicle" (brand_id ASC)
;

CREATE INDEX "IXFK_RoadVehicle_RoadVehicleFeature_02" ON "Analytics"."RoadVehicle" (registration_type_id ASC)
;

CREATE INDEX "IXFK_RoadVehicle_RoadVehicleFeature_03" ON "Analytics"."RoadVehicle" (status_id ASC)
;

CREATE INDEX "IXFK_RoadVehicle_RoadVehicleFeature_04" ON "Analytics"."RoadVehicle" (type_id ASC)
;

CREATE INDEX "IXFK_RoadVehicle_RoadVehicleFeature_05" ON "Analytics"."RoadVehicle" (subtype_id ASC)
;

CREATE INDEX "IXFK_RoadVehicle_Vehicle" ON "Analytics"."RoadVehicle" (id ASC)
;

ALTER TABLE "Analytics"."RoadVehicleDictionary" ADD CONSTRAINT "PK_RoadVehicleDictionary"
  PRIMARY KEY (id)
;

ALTER TABLE "Analytics"."RoadVehicleDictionary" ADD CONSTRAINT "CH_RoadVehicleDictionary" CHECK (dictionary_type IN ('ROAD_VEHICLE_STATUS_TYPE', 'ROAD_VEHICLE_REGISTRATION_TYPE', 'ROAD_VEHICLE_PLATE_TYPE', 'ROAD_VEHICLE_REGISTRATION_IDENTITY_TYPE', 'ROAD_VEHICLE_REGISTRATION_CERTIFICATE_TYPE', 'ROAD_VEHICLE_BRAND_TYPE', 'ROAD_VEHICLE_TYPE', 'ROAD_VEHICLE_SUBTYPE', 'ROAD_VEHICLE_REGISTRATION_CERTIFICATE_STATUS_TYPE', 'ROAD_VEHICLE_REGISTRATION_CERTIFICATE_WITHDRAWAL_TYPE', 'NOS'))
;

ALTER TABLE "Analytics"."RoadVehicleInsurancePolicy" ADD CONSTRAINT "PK_RoadVehicleInsurancePolicy"
  PRIMARY KEY (id)
;

CREATE INDEX "IXFK_RoadVehicleInsurancePolicy_RoadVehicle" ON "Analytics"."RoadVehicleInsurancePolicy" (road_vehicle_id ASC)
;

ALTER TABLE "Analytics"."RoadVehicleRegistration" ADD CONSTRAINT "PK_RoadVehicleRegistration"
  PRIMARY KEY (id)
;

CREATE INDEX "IXFK_RoadVehicleRegistration_Event" ON "Analytics"."RoadVehicleRegistration" (id ASC)
;

CREATE INDEX "IXFK_RoadVehicleRegistration_RoadVehicleDictionary" ON "Analytics"."RoadVehicleRegistration" (registration_type ASC)
;

ALTER TABLE "Analytics"."RoadVehicleRegistrationCertificate" ADD CONSTRAINT "PK_RoadVehicleRegistrationCertificate"
  PRIMARY KEY (id)
;

CREATE INDEX "IXFK_RoadVehicleRegistrationCertificate_IdentityDocument" ON "Analytics"."RoadVehicleRegistrationCertificate" (id ASC)
;

CREATE INDEX "IXFK_RoadVehicleRegistrationCertificate_RoadVehicleDictionary" ON "Analytics"."RoadVehicleRegistrationCertificate" (type ASC)
;

CREATE INDEX "IXFK_RoadVehicleRegistrationCertificate_RoadVehicleDictionary_02" ON "Analytics"."RoadVehicleRegistrationCertificate" (status ASC)
;

ALTER TABLE "Analytics"."RoadVehicleRegistrationCertificateWithdrawal" ADD CONSTRAINT "PK_RoadVehicleRegistrationCertificateWithdrawal"
  PRIMARY KEY (id)
;

CREATE INDEX "IXFK_RoadVehicleRegistrationCertificateWithdrawal_RoadVehicleDictionary" ON "Analytics"."RoadVehicleRegistrationCertificateWithdrawal" (purpose ASC)
;

CREATE INDEX "IXFK_RoadVehicleRegistrationCertificateWithdrawal_RoadVehicleRegistrationCertificate" ON "Analytics"."RoadVehicleRegistrationCertificateWithdrawal" (road_vehicle_registration_certificate_id ASC)
;

ALTER TABLE "Analytics"."RoadVehicleRegistrationIdentity" ADD CONSTRAINT "PK_RoadVehicleRegistrationIdentity"
  PRIMARY KEY (id)
;

CREATE INDEX "IXFK_RoadVehicleRegistrationIdentity_RoadVehicleDictionary" ON "Analytics"."RoadVehicleRegistrationIdentity" (type ASC)
;

CREATE INDEX "IXFK_RoadVehicleRegistrationIdentity_RoadVehicleRegistrationCertificate" ON "Analytics"."RoadVehicleRegistrationIdentity" (road_vehicle_registration_certificate_id ASC)
;

ALTER TABLE "Analytics"."RoadVehicleRegistrationPlate" ADD CONSTRAINT "PK_RoadVehicleRegistrationPlate"
  PRIMARY KEY (id)
;

CREATE INDEX "IXFK_RoadVehicleRegistrationPlate_Country" ON "Analytics"."RoadVehicleRegistrationPlate" (issuing_country_id ASC)
;

CREATE INDEX "IXFK_RoadVehicleRegistrationPlate_RoadVehicle" ON "Analytics"."RoadVehicleRegistrationPlate" (road_vehicle_id ASC)
;

CREATE INDEX "IXFK_RoadVehicleRegistrationPlate_RoadVehicleDictionary" ON "Analytics"."RoadVehicleRegistrationPlate" (type ASC)
;

ALTER TABLE "Analytics"."SourceQueryContext" ADD CONSTRAINT "PK_SourceQueryContext"
  PRIMARY KEY (id)
;

CREATE INDEX "IXFK_SourceQueryContext_AnalyticalContext" ON "Analytics"."SourceQueryContext" (analytical_context_id ASC)
;

ALTER TABLE "Analytics"."Surname" ADD CONSTRAINT "PK_Surname"
  PRIMARY KEY (id)
;

ALTER TABLE "Analytics"."Surname" ADD CONSTRAINT "CH_Surname_Type" CHECK (type in ('PRIMARY', 'OTHER', 'PREVIOUS', 'AT_BIRTH', 'MAIDEN'))
;

CREATE INDEX "IXFK_Surname_Person" ON "Analytics"."Surname" (person_id ASC)
;

ALTER TABLE "Analytics"."SurnameAlternative" ADD CONSTRAINT "PK_SurnameAlternative"
  PRIMARY KEY (id)
;

CREATE INDEX "IXFK_SurnameAlternative_Surname" ON "Analytics"."SurnameAlternative" (surname_id ASC)
;

ALTER TABLE "Analytics"."UIViewContext" ADD CONSTRAINT "PK_UIViewContext"
  PRIMARY KEY (id)
;

ALTER TABLE "Analytics"."UIViewContext" ADD CONSTRAINT "CH_UIViewContext" CHECK (type IN ('PERSON_PROFILE', 'GRAPH', 'MAP', 'TIMELINE', 'NOS'))
;

ALTER TABLE "Analytics"."User" ADD CONSTRAINT "PK_User"
  PRIMARY KEY (id)
;

ALTER TABLE "Analytics"."UserCaseAssociation" ADD CONSTRAINT "PK_UserCaseAssociation"
  PRIMARY KEY (id)
;

CREATE INDEX "IXFK_UserCaseAssociation_Case" ON "Analytics"."UserCaseAssociation" (case_id ASC)
;

CREATE INDEX "IXFK_UserCaseAssociation_User" ON "Analytics"."UserCaseAssociation" (user_id ASC)
;

ALTER TABLE "Analytics"."Vehicle" ADD CONSTRAINT "PK_Vehicle"
  PRIMARY KEY (id)
;

ALTER TABLE "Analytics"."Vehicle" ADD CONSTRAINT "CH_Vehicle" CHECK (type IN ('ROAD_VEHICLE', 'NOS'))
;

CREATE INDEX "IXFK_Vehicle_Object" ON "Analytics"."Vehicle" (id ASC)
;

ALTER TABLE "Analytics"."VehicleObjectAssociation" ADD CONSTRAINT "PK_VehicleObjectAssociation"
  PRIMARY KEY (id)
;

ALTER TABLE "Analytics"."VehicleObjectAssociation" ADD CONSTRAINT "CH_VehicleObjectAssociation" CHECK (type IN ('ROAD_VEHICLE_OWNER', 'NOS'))
;

CREATE INDEX "IXFK_VehicleObjectAssociation_Association" ON "Analytics"."VehicleObjectAssociation" (id ASC)
;

CREATE INDEX "IXFK_VehicleObjectAssociation_Object" ON "Analytics"."VehicleObjectAssociation" (object_id ASC)
;

CREATE INDEX "IXFK_VehicleObjectAssociation_Vehicle" ON "Analytics"."VehicleObjectAssociation" (vehicle_id ASC)
;

ALTER TABLE "Analytics"."Visa" ADD CONSTRAINT "PK_Visa"
  PRIMARY KEY (id)
;

ALTER TABLE "Analytics"."Visa" ADD CONSTRAINT "CH_VisaType" CHECK (type IN ('NOS'))
;

ALTER TABLE "Analytics"."Visa" ADD CONSTRAINT "CH_VisaStickerStatus" CHECK (sticker_status IN ('NOS'))
;

CREATE INDEX "IXFK_Visa_IdentityDocument" ON "Analytics"."Visa" (id ASC)
;

CREATE INDEX "IXFK_Visa_Passport" ON "Analytics"."Visa" (passport_id ASC)
;

ALTER TABLE "Analytics"."VisaApplication" ADD CONSTRAINT "PK_VisaApplication"
  PRIMARY KEY (id)
;

ALTER TABLE "Analytics"."VisaApplication" ADD CONSTRAINT "CH_VisaApplication_01" CHECK (number_of_entries IN ('NOS'))
;

ALTER TABLE "Analytics"."VisaApplication" ADD CONSTRAINT "CH_VisaApplication_02" CHECK (purpose_code IN ('NOS'))
;

ALTER TABLE "Analytics"."VisaApplication" ADD CONSTRAINT "CH_VisaApplication_03" CHECK (requested_visa_type IN ('NOS'))
;

CREATE INDEX "IXFK_VisaApplication_Country" ON "Analytics"."VisaApplication" (destination_country_id ASC)
;

CREATE INDEX "IXFK_VisaApplication_Event" ON "Analytics"."VisaApplication" (id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE "Analytics"."Address" ADD CONSTRAINT "FK_Address_Location"
  FOREIGN KEY (id) REFERENCES "Analytics"."Location" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."AddressAlternativeName" ADD CONSTRAINT "FK_AddressAlternativeName_Address"
  FOREIGN KEY (address_id) REFERENCES "Analytics"."Address" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."Association" ADD CONSTRAINT "FK_Association_AnalyticalContext"
  FOREIGN KEY (analytical_context_id) REFERENCES "Analytics"."AnalyticalContext" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."AssociationSourceQueryAssociation" ADD CONSTRAINT "FK_AssociationSourceQueryAssociation_Association"
  FOREIGN KEY (association_id) REFERENCES "Analytics"."Association" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."AssociationSourceQueryAssociation" ADD CONSTRAINT "FK_AssociationSourceQueryAssociation_SourceQueryContext"
  FOREIGN KEY (source_query_id) REFERENCES "Analytics"."SourceQueryContext" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."AssociationUIViewAssocation" ADD CONSTRAINT "FK_AssociationUIViewAssocation_Association"
  FOREIGN KEY (association_id) REFERENCES "Analytics"."Association" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."AssociationUIViewAssocation" ADD CONSTRAINT "FK_AssociationUIViewAssocation_UIViewContext"
  FOREIGN KEY (ui_view_context_id) REFERENCES "Analytics"."UIViewContext" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."Authority" ADD CONSTRAINT "FK_Authority_GovernmentOrganisation"
  FOREIGN KEY (id) REFERENCES "Analytics"."GovernmentOrganisation" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."Binary" ADD CONSTRAINT "FK_Binary_AnalyticalContext"
  FOREIGN KEY (analytical_context_id) REFERENCES "Analytics"."AnalyticalContext" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."BinarySourceQueryAssociation" ADD CONSTRAINT "FK_BinarySourceQueryAssociation_SourceQueryContext"
  FOREIGN KEY (source_query_id) REFERENCES "Analytics"."SourceQueryContext" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."BinaryUIViewAssociation" ADD CONSTRAINT "FK_BinaryUIViewAssociation_Binary"
  FOREIGN KEY (binary_id) REFERENCES "Analytics"."Binary" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."BinaryUIViewAssociation" ADD CONSTRAINT "FK_BinaryUIViewAssociation_UIViewContext"
  FOREIGN KEY (ui_view_context_id) REFERENCES "Analytics"."UIViewContext" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."BorderCross" ADD CONSTRAINT "FK_BorderCross_Event"
  FOREIGN KEY (id) REFERENCES "Analytics"."Event" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."BorderCrossingPoint" ADD CONSTRAINT "FK_BorderCrossingPoint_Facility"
  FOREIGN KEY (id) REFERENCES "Analytics"."Facility" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."BusinessEntity" ADD CONSTRAINT "FK_BusinessEntity_Organisation"
  FOREIGN KEY (id) REFERENCES "Analytics"."Organisation" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."BusinessEntityAlternativeName" ADD CONSTRAINT "FK_BusinessEntityAlternativeName_BusinessEntity"
  FOREIGN KEY (business_entity_id) REFERENCES "Analytics"."BusinessEntity" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."BusinessEntityLegalChanges" ADD CONSTRAINT "FK_BusinessEntityLegalChanges_BusinessEntity"
  FOREIGN KEY (business_entity_id) REFERENCES "Analytics"."BusinessEntity" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."CarRegistrationCertificate" ADD CONSTRAINT "FK_CarRegistrationCertificate_IdentityDocument"
  FOREIGN KEY (id) REFERENCES "Analytics"."IdentityDocument" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."Case" ADD CONSTRAINT "FK_Case_AnalyticalContext"
  FOREIGN KEY (id) REFERENCES "Analytics"."AnalyticalContext" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."ContactDetails" ADD CONSTRAINT "FK_ContactDetails_Person"
  FOREIGN KEY (person_id) REFERENCES "Analytics"."Person" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."Document" ADD CONSTRAINT "FK_Document_AnalyticalContext"
  FOREIGN KEY (analytical_context_id) REFERENCES "Analytics"."AnalyticalContext" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."DocumentSourceQueryAssociation" ADD CONSTRAINT "FK_DocumentSourceQueryAssociation_Document"
  FOREIGN KEY (document_id) REFERENCES "Analytics"."Document" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."DocumentSourceQueryAssociation" ADD CONSTRAINT "FK_DocumentSourceQueryAssociation_SourceQueryContext"
  FOREIGN KEY (source_query_id) REFERENCES "Analytics"."SourceQueryContext" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."DocumentUIViewAssociation" ADD CONSTRAINT "FK_DocumentUIViewAssociation_Document"
  FOREIGN KEY (document_id) REFERENCES "Analytics"."Document" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."DocumentUIViewAssociation" ADD CONSTRAINT "FK_DocumentUIViewAssociation_UIViewContext"
  FOREIGN KEY (ui_view_context_id) REFERENCES "Analytics"."UIViewContext" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."Event" ADD CONSTRAINT "FK_Event_AnalyticalContext"
  FOREIGN KEY (analytical_context_id) REFERENCES "Analytics"."AnalyticalContext" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."EventDocumentAssociation" ADD CONSTRAINT "FK_EventDocumentAssociation_Association"
  FOREIGN KEY (id) REFERENCES "Analytics"."Association" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."EventDocumentAssociation" ADD CONSTRAINT "FK_EventDocumentAssociation_Document"
  FOREIGN KEY (document_id) REFERENCES "Analytics"."Document" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."EventDocumentAssociation" ADD CONSTRAINT "FK_EventDocumentAssociation_Event"
  FOREIGN KEY (event_id) REFERENCES "Analytics"."Event" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."EventLocationAssociation" ADD CONSTRAINT "FK_EventLocationAssociation_Association"
  FOREIGN KEY (id) REFERENCES "Analytics"."Association" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."EventLocationAssociation" ADD CONSTRAINT "FK_EventLocationAssociation_Event"
  FOREIGN KEY (event_id) REFERENCES "Analytics"."Event" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."EventLocationAssociation" ADD CONSTRAINT "FK_EventLocationAssociation_Location"
  FOREIGN KEY (location_id) REFERENCES "Analytics"."Location" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."EventSourceQueryAssociation" ADD CONSTRAINT "FK_EventSourceQueryAssociation_Event"
  FOREIGN KEY (event_id) REFERENCES "Analytics"."Event" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."EventSourceQueryAssociation" ADD CONSTRAINT "FK_EventSourceQueryAssociation_SourceQueryContext"
  FOREIGN KEY (source_query_id) REFERENCES "Analytics"."SourceQueryContext" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."EventUIViewAssociation" ADD CONSTRAINT "FK_EventUIViewAssociation_Event"
  FOREIGN KEY (event_id) REFERENCES "Analytics"."Event" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."EventUIViewAssociation" ADD CONSTRAINT "FK_EventUIViewAssociation_UIViewContext"
  FOREIGN KEY (ui_view_context_id) REFERENCES "Analytics"."UIViewContext" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."Facility" ADD CONSTRAINT "FK_Facility_Object"
  FOREIGN KEY (id) REFERENCES "Analytics"."Object" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."FacilityOrganisationAssociation" ADD CONSTRAINT "FK_FacilityOrganisationAssociation_Association"
  FOREIGN KEY (id) REFERENCES "Analytics"."Association" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."FacilityOrganisationAssociation" ADD CONSTRAINT "FK_FacilityOrganisationAssociation_Facility"
  FOREIGN KEY (facility_id) REFERENCES "Analytics"."Facility" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."FacilityOrganisationAssociation" ADD CONSTRAINT "FK_FacilityOrganisationAssociation_Organisation"
  FOREIGN KEY (organisation_id) REFERENCES "Analytics"."Organisation" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."ForeignerIdentityCard" ADD CONSTRAINT "FK_ForeignerIdentityCard_Country"
  FOREIGN KEY (issuer_country_id) REFERENCES "Analytics"."Country" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."ForeignerIdentityCard" ADD CONSTRAINT "FK_ForeignerIdentityCard_IdentityDocument"
  FOREIGN KEY (id) REFERENCES "Analytics"."IdentityDocument" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."GeoPoint" ADD CONSTRAINT "FK_GeoPoint_Location"
  FOREIGN KEY (id) REFERENCES "Analytics"."Location" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."GovernmentOrganisation" ADD CONSTRAINT "FK_GovernmentOrganisation_Organisation"
  FOREIGN KEY (id) REFERENCES "Analytics"."Organisation" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."IdentityDocument" ADD CONSTRAINT "FK_IdentityDocument_Document"
  FOREIGN KEY (id) REFERENCES "Analytics"."Document" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."Location" ADD CONSTRAINT "FK_Location_AnalyticalContext"
  FOREIGN KEY (analytical_context_id) REFERENCES "Analytics"."AnalyticalContext" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."Location" ADD CONSTRAINT "FK_Location_Country"
  FOREIGN KEY (country_id) REFERENCES "Analytics"."Country" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."LocationSourceQueryAssociation" ADD CONSTRAINT "FK_LocationSourceQueryAssociation_Location"
  FOREIGN KEY (location_id) REFERENCES "Analytics"."Location" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."LocationSourceQueryAssociation" ADD CONSTRAINT "FK_LocationSourceQueryAssociation_SourceQueryContext"
  FOREIGN KEY (source_query_id) REFERENCES "Analytics"."SourceQueryContext" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."LocationUIViewAssociation" ADD CONSTRAINT "FK_LocationUIViewAssociation_Location"
  FOREIGN KEY (location_id) REFERENCES "Analytics"."Location" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."LocationUIViewAssociation" ADD CONSTRAINT "FK_LocationUIViewAssociation_UIViewContext"
  FOREIGN KEY (ui_view_context_id) REFERENCES "Analytics"."UIViewContext" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."Migration" ADD CONSTRAINT "FK_Migration_Country"
  FOREIGN KEY (country_id) REFERENCES "Analytics"."Country" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."Migration" ADD CONSTRAINT "FK_Migration_Person"
  FOREIGN KEY (person_id) REFERENCES "Analytics"."Person" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."Name" ADD CONSTRAINT "FK_Name_Person"
  FOREIGN KEY (person_id) REFERENCES "Analytics"."Person" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."NameAlternative" ADD CONSTRAINT "FK_NameAlternative_Name"
  FOREIGN KEY (name_id) REFERENCES "Analytics"."Name" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."Object" ADD CONSTRAINT "FK_Object_AnalyticalContext"
  FOREIGN KEY (analytical_context_id) REFERENCES "Analytics"."AnalyticalContext" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."ObjectBinaryAssociation" ADD CONSTRAINT "FK_ObjectBinaryAssociation_Association"
  FOREIGN KEY (id) REFERENCES "Analytics"."Association" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."ObjectBinaryAssociation" ADD CONSTRAINT "FK_ObjectBinaryAssociation_Binary"
  FOREIGN KEY (binary_id) REFERENCES "Analytics"."Binary" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."ObjectBinaryAssociation" ADD CONSTRAINT "FK_ObjectBinaryAssociation_Object"
  FOREIGN KEY (object_id) REFERENCES "Analytics"."Object" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."ObjectDocumentAssociation" ADD CONSTRAINT "FK_ObjectDocumentAssociation_Association"
  FOREIGN KEY (id) REFERENCES "Analytics"."Association" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."ObjectDocumentAssociation" ADD CONSTRAINT "FK_ObjectDocumentAssociation_Document"
  FOREIGN KEY (document_id) REFERENCES "Analytics"."Document" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."ObjectDocumentAssociation" ADD CONSTRAINT "FK_ObjectDocumentAssociation_Object"
  FOREIGN KEY (object_id) REFERENCES "Analytics"."Object" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."ObjectEventAssociation" ADD CONSTRAINT "FK_ObjectEventAssociation_Association"
  FOREIGN KEY (id) REFERENCES "Analytics"."Association" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."ObjectEventAssociation" ADD CONSTRAINT "FK_ObjectEventAssociation_Event"
  FOREIGN KEY (event_id) REFERENCES "Analytics"."Event" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."ObjectEventAssociation" ADD CONSTRAINT "FK_ObjectEventAssociation_Object"
  FOREIGN KEY (object_id) REFERENCES "Analytics"."Object" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."ObjectLocationAssociation" ADD CONSTRAINT "FK_ObjectLocationAssociation_Association"
  FOREIGN KEY (id) REFERENCES "Analytics"."Association" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."ObjectLocationAssociation" ADD CONSTRAINT "FK_ObjectLocationAssociation_Location"
  FOREIGN KEY (location_id) REFERENCES "Analytics"."Location" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."ObjectLocationAssociation" ADD CONSTRAINT "FK_ObjectLocationAssociation_Object"
  FOREIGN KEY (object_id) REFERENCES "Analytics"."Object" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."ObjectSourceQueryAssociation" ADD CONSTRAINT "FK_ObjectSourceQueryAssociation_Object"
  FOREIGN KEY (object_id) REFERENCES "Analytics"."Object" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."ObjectSourceQueryAssociation" ADD CONSTRAINT "FK_ObjectSourceQueryAssociation_SourceQueryContext"
  FOREIGN KEY (source_query_id) REFERENCES "Analytics"."SourceQueryContext" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."ObjectUIViewAssociation" ADD CONSTRAINT "FK_ObjectUIViewAssociation_Object"
  FOREIGN KEY (object_id) REFERENCES "Analytics"."Object" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."ObjectUIViewAssociation" ADD CONSTRAINT "FK_ObjectUIViewAssociation_UIViewContext"
  FOREIGN KEY (ui_view_context_id) REFERENCES "Analytics"."UIViewContext" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."Organisation" ADD CONSTRAINT "FK_Organisation_Country"
  FOREIGN KEY (country_id) REFERENCES "Analytics"."Country" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."Organisation" ADD CONSTRAINT "FK_Organisation_Object"
  FOREIGN KEY (id) REFERENCES "Analytics"."Object" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."OrganisationOrganisationAssociation" ADD CONSTRAINT "FK_OrganisationOrganisationAssociation_Association"
  FOREIGN KEY (id) REFERENCES "Analytics"."Association" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."OrganisationOrganisationAssociation" ADD CONSTRAINT "FK_OrganisationOrganisationAssociation_Organisation"
  FOREIGN KEY (subject_organisation_id) REFERENCES "Analytics"."Organisation" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."OrganisationOrganisationAssociation" ADD CONSTRAINT "FK_OrganisationOrganisationAssociation_Organisation_02"
  FOREIGN KEY (object_organisation_id) REFERENCES "Analytics"."Organisation" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."OrganisationPersonAssociation" ADD CONSTRAINT "FK_OrganisationPersonAssociation_Association"
  FOREIGN KEY (id) REFERENCES "Analytics"."Association" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."OrganisationPersonAssociation" ADD CONSTRAINT "FK_OrganisationPersonAssociation_Organisation"
  FOREIGN KEY (organisation_id) REFERENCES "Analytics"."Organisation" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."OrganisationPersonAssociation" ADD CONSTRAINT "FK_OrganisationPersonAssociation_Person"
  FOREIGN KEY (person_id) REFERENCES "Analytics"."Person" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."Passport" ADD CONSTRAINT "FK_Passport_IdentityDocument"
  FOREIGN KEY (id) REFERENCES "Analytics"."IdentityDocument" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."Person" ADD CONSTRAINT "FK_Person_Birth_Citizenship"
  FOREIGN KEY (birth_citizenship_id) REFERENCES "Analytics"."Citizenship" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."Person" ADD CONSTRAINT "FK_Person_Birth_Country"
  FOREIGN KEY (birth_country_id) REFERENCES "Analytics"."Country" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."Person" ADD CONSTRAINT "FK_Person_Home_Country"
  FOREIGN KEY (home_country_id) REFERENCES "Analytics"."Country" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."Person" ADD CONSTRAINT "FK_Person_Object"
  FOREIGN KEY (id) REFERENCES "Analytics"."Object" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."Person" ADD CONSTRAINT "FK_Person_Place"
  FOREIGN KEY (birth_place_id) REFERENCES "Analytics"."Place" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."PersonalAccess" ADD CONSTRAINT "FK_PersonalAccess_AnalyticalContext"
  FOREIGN KEY (id) REFERENCES "Analytics"."AnalyticalContext" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."PersonalAccess" ADD CONSTRAINT "FK_PersonalAccess_User"
  FOREIGN KEY (id) REFERENCES "Analytics"."User" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."PersonPersonAssociation" ADD CONSTRAINT "FK_PersonPersonAssociation_Association"
  FOREIGN KEY (id) REFERENCES "Analytics"."Association" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."PersonPersonAssociation" ADD CONSTRAINT "FK_PersonPersonAssociation_Person"
  FOREIGN KEY (object_person_id) REFERENCES "Analytics"."Person" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."PersonPersonAssociation" ADD CONSTRAINT "FK_PersonPersonAssociation_Person_02"
  FOREIGN KEY (subject_person_id) REFERENCES "Analytics"."Person" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."Picture" ADD CONSTRAINT "FK_Picture_Binary"
  FOREIGN KEY (id) REFERENCES "Analytics"."Binary" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."Place" ADD CONSTRAINT "FK_Place_Location"
  FOREIGN KEY (id) REFERENCES "Analytics"."Location" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."PlaceAlternativeName" ADD CONSTRAINT "FK_PlaceAlternativeName_Place"
  FOREIGN KEY (place_id) REFERENCES "Analytics"."Place" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."PolishIdentityCard" ADD CONSTRAINT "FK_PolishIdentityCard_IdentityDocument"
  FOREIGN KEY (id) REFERENCES "Analytics"."IdentityDocument" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."RoadBorderCrossing" ADD CONSTRAINT "FK_RoadBorderCrossing_BorderCross"
  FOREIGN KEY (id) REFERENCES "Analytics"."BorderCross" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."RoadBorderCrossingPoint" ADD CONSTRAINT "FK_RoadBorderCrossingPoint_BorderCrossingPoint"
  FOREIGN KEY (id) REFERENCES "Analytics"."BorderCrossingPoint" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."RoadCheckPointTransition" ADD CONSTRAINT "FK_RoadCheckPointTransition_Event"
  FOREIGN KEY (id) REFERENCES "Analytics"."Event" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."RoadVehicle" ADD CONSTRAINT "FK_RoadVehicle_Country"
  FOREIGN KEY (abroad_status_registration_country_id) REFERENCES "Analytics"."Country" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."RoadVehicle" ADD CONSTRAINT "FK_RoadVehicle_RoadVehicleFeature"
  FOREIGN KEY (brand_id) REFERENCES "Analytics"."RoadVehicleDictionary" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."RoadVehicle" ADD CONSTRAINT "FK_RoadVehicle_RoadVehicleFeature_02"
  FOREIGN KEY (registration_type_id) REFERENCES "Analytics"."RoadVehicleDictionary" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."RoadVehicle" ADD CONSTRAINT "FK_RoadVehicle_RoadVehicleFeature_03"
  FOREIGN KEY (status_id) REFERENCES "Analytics"."RoadVehicleDictionary" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."RoadVehicle" ADD CONSTRAINT "FK_RoadVehicle_RoadVehicleFeature_04"
  FOREIGN KEY (type_id) REFERENCES "Analytics"."RoadVehicleDictionary" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."RoadVehicle" ADD CONSTRAINT "FK_RoadVehicle_RoadVehicleFeature_05"
  FOREIGN KEY (subtype_id) REFERENCES "Analytics"."RoadVehicleDictionary" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."RoadVehicle" ADD CONSTRAINT "FK_RoadVehicle_Vehicle"
  FOREIGN KEY (id) REFERENCES "Analytics"."Vehicle" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."RoadVehicleInsurancePolicy" ADD CONSTRAINT "FK_RoadVehicleInsurancePolicy_RoadVehicle"
  FOREIGN KEY (road_vehicle_id) REFERENCES "Analytics"."RoadVehicle" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."RoadVehicleRegistration" ADD CONSTRAINT "FK_RoadVehicleRegistration_Event"
  FOREIGN KEY (id) REFERENCES "Analytics"."Event" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."RoadVehicleRegistration" ADD CONSTRAINT "FK_RoadVehicleRegistration_RoadVehicleDictionary"
  FOREIGN KEY (registration_type) REFERENCES "Analytics"."RoadVehicleDictionary" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."RoadVehicleRegistrationCertificate" ADD CONSTRAINT "FK_RoadVehicleRegistrationCertificate_IdentityDocument"
  FOREIGN KEY (id) REFERENCES "Analytics"."IdentityDocument" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."RoadVehicleRegistrationCertificate" ADD CONSTRAINT "FK_RoadVehicleRegistrationCertificate_RoadVehicleDictionary"
  FOREIGN KEY (type) REFERENCES "Analytics"."RoadVehicleDictionary" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."RoadVehicleRegistrationCertificate" ADD CONSTRAINT "FK_RoadVehicleRegistrationCertificate_RoadVehicleDictionary_02"
  FOREIGN KEY (status) REFERENCES "Analytics"."RoadVehicleDictionary" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."RoadVehicleRegistrationCertificateWithdrawal" ADD CONSTRAINT "FK_RoadVehicleRegistrationCertificateWithdrawal_RoadVehicleDictionary"
  FOREIGN KEY (purpose) REFERENCES "Analytics"."RoadVehicleDictionary" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."RoadVehicleRegistrationCertificateWithdrawal" ADD CONSTRAINT "FK_RoadVehicleRegistrationCertificateWithdrawal_RoadVehicleRegistrationCertificate"
  FOREIGN KEY (road_vehicle_registration_certificate_id) REFERENCES "Analytics"."RoadVehicleRegistrationCertificate" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."RoadVehicleRegistrationIdentity" ADD CONSTRAINT "FK_RoadVehicleRegistrationIdentity_RoadVehicleDictionary"
  FOREIGN KEY (type) REFERENCES "Analytics"."RoadVehicleDictionary" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."RoadVehicleRegistrationIdentity" ADD CONSTRAINT "FK_RoadVehicleRegistrationIdentity_RoadVehicleRegistrationCertificate"
  FOREIGN KEY (road_vehicle_registration_certificate_id) REFERENCES "Analytics"."RoadVehicleRegistrationCertificate" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."RoadVehicleRegistrationPlate" ADD CONSTRAINT "FK_RoadVehicleRegistrationPlate_Country"
  FOREIGN KEY (issuing_country_id) REFERENCES "Analytics"."Country" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."RoadVehicleRegistrationPlate" ADD CONSTRAINT "FK_RoadVehicleRegistrationPlate_RoadVehicle"
  FOREIGN KEY (road_vehicle_id) REFERENCES "Analytics"."RoadVehicle" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."RoadVehicleRegistrationPlate" ADD CONSTRAINT "FK_RoadVehicleRegistrationPlate_RoadVehicleDictionary"
  FOREIGN KEY (type) REFERENCES "Analytics"."RoadVehicleDictionary" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."SourceQueryContext" ADD CONSTRAINT "FK_SourceQueryContext_AnalyticalContext"
  FOREIGN KEY (analytical_context_id) REFERENCES "Analytics"."AnalyticalContext" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."Surname" ADD CONSTRAINT "FK_Surname_Person"
  FOREIGN KEY (person_id) REFERENCES "Analytics"."Person" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."SurnameAlternative" ADD CONSTRAINT "FK_SurnameAlternative_Surname"
  FOREIGN KEY (surname_id) REFERENCES "Analytics"."Surname" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."UserCaseAssociation" ADD CONSTRAINT "FK_UserCaseAssociation_Case"
  FOREIGN KEY (case_id) REFERENCES "Analytics"."Case" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."UserCaseAssociation" ADD CONSTRAINT "FK_UserCaseAssociation_User"
  FOREIGN KEY (user_id) REFERENCES "Analytics"."User" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."Vehicle" ADD CONSTRAINT "FK_Vehicle_Object"
  FOREIGN KEY (id) REFERENCES "Analytics"."Object" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."VehicleObjectAssociation" ADD CONSTRAINT "FK_VehicleObjectAssociation_Association"
  FOREIGN KEY (id) REFERENCES "Analytics"."Association" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."VehicleObjectAssociation" ADD CONSTRAINT "FK_VehicleObjectAssociation_Object"
  FOREIGN KEY (object_id) REFERENCES "Analytics"."Object" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."VehicleObjectAssociation" ADD CONSTRAINT "FK_VehicleObjectAssociation_Vehicle"
  FOREIGN KEY (vehicle_id) REFERENCES "Analytics"."Vehicle" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."Visa" ADD CONSTRAINT "FK_Visa_IdentityDocument"
  FOREIGN KEY (id) REFERENCES "Analytics"."IdentityDocument" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."Visa" ADD CONSTRAINT "FK_Visa_Passport"
  FOREIGN KEY (passport_id) REFERENCES "Analytics"."Passport" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."VisaApplication" ADD CONSTRAINT "FK_VisaApplication_Country"
  FOREIGN KEY (destination_country_id) REFERENCES "Analytics"."Country" (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Analytics"."VisaApplication" ADD CONSTRAINT "FK_VisaApplication_Event"
  FOREIGN KEY (id) REFERENCES "Analytics"."Event" (id) ON DELETE No Action ON UPDATE No Action
;
