create table candidates
(
    id         BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(20) default NULL,
    last_name  VARCHAR(20) default NULL,
    PRIMARY KEY (id)
);
create table elections
(
    id            BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    title         VARCHAR(20) default NULL,
    election_date DATE        default NULL,
    PRIMARY KEY (id)
);
create table electors
(
    id              BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    first_name      VARCHAR(20) default NULL,
    last_name       VARCHAR(20) default NULL,
    document_number VARCHAR(20) DEFAULT NULL,
    PRIMARY KEY (id)
);
create table candidates_elections
(
    candidate_id BIGINT NOT NULL REFERENCES candidates (id) ON DELETE CASCADE,
    election_id  BIGINT NOT NULL REFERENCES elections (id) ON DELETE CASCADE,
    votes        BIGINT default NULL,
    PRIMARY KEY (candidate_id, election_id)
);
create table electors_elections
(
    elector_id        BIGINT NOT NULL REFERENCES electors (id) ON DELETE CASCADE,
    election_id       BIGINT NOT NULL REFERENCES elections (id) ON DELETE CASCADE,
    elector_voted   BOOLEAN default false,
    elector_blocked BOOLEAN default false,
    PRIMARY KEY (elector_id, election_id)
);